ad/config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :advertisers do
          collection do
              post :selected
              
      end
    end
    resources :advertises  do
         collection do
              post :selected
              post :creatss
              
        end
    end
  resources :advertises 

 resources :advocates
 
 resources :tasks

 resources :informations 

end
resources :advertises
resources :advertisers
resources :advocates

end

ad/app/models/advertise.rb
class Advertise < ActiveRecord::Base
	belongs_to :advertiser
        
end

ad/app/models/advertiser.rb
class Advertiser < ActiveRecord::Base
	has_many :advertises
	
end

ad/app/models/advocate.rb
class Advocate < ActiveRecord::Base
end

ad/app/models/information.rb
class Information < ActiveRecord::Base
end

ad/app/models/task.rb
class Task < ActiveRecord::Base
end

ad/app/controllers/admin/advertisers_controller.rb
class Admin::AdvertisersController < ApplicationController
	before_action :authenticate
   def index
		
	end
    def selected
		if params[:keyword].empty?
			 @advertisers = Advertiser.all
		else 
			@advertisers = Advertiser.where(["#{params[:option]} like?","%#{params[:keyword]}%"])
		end

		
		
	end
  def show
        advertisers = Advertiser.find(params[:id])
    @advertisers = advertisers.advertiser
     
  end
    def edit
   		@advertisers = Advertiser.find(params[:id])
	end
    def update
  		@advertisers = Advertiser.find(params[:id])
  		@advertisers.update(advertiser_params)

  		redirect_to :action => :index
	end
   def destroy
  		@advertisers = Advertiser.find(params[:id])
  		@advertisers.destroy

  		 redirect_to :action => :index
	end
    # ....

    protected

    def authenticate
       authenticate_or_request_with_http_basic do |user_name, password|
           user_name == "username" && password == "password"
       end
    end

    private

    def advertiser_params
   params.require(:advertiser).permit(:name, :email, :advertiser_id, :phone, :account, :password, :count)
end
end

ad/app/controllers/admin/advertises_controller.rb
class Admin::AdvertisesController < ApplicationController
	before_action :authenticate
    
    def index
		
	end
    def selected
		if params[:keyword]
			@advertises = Advertise.where(["#{params[:option]} like?","%#{params[:keyword]}%"])
		else 
			@advertises = Advertise.all
		end
	end
 def show
     		advertises = Advertise.find(params[:id])
		@advertises = advertises.advertiser
		 
	end
		
    # ....

    protected

    def authenticate
       authenticate_or_request_with_http_basic do |user_name, password|
           user_name == "username" && password == "password"
       end
    end
end

ad/app/controllers/advertisers_controller.rb
class AdvertisersController < ApplicationController
	def index
		@advertisers = Advertiser.all 
		render :json => @advertisers.to_json
	end
	def selected
		if params[:keyword]
			@advertisers = Advertiser.where(["#{params[:option]} like?","%#{params[:keyword]}%"])
		else 
			@advertisers = Advertiser.all
		end

		
		
	end
end

ad/app/controllers/advertises_controller.rb
class AdvertisesController < ApplicationController
	
    
    def index

		@advertises = Advocate.all.select("name")
		render :json =>@advertises
	end
   

    protected

  
end

ad/app/controllers/advocates_controller.rb
class AdvocatesController < ApplicationController
	def index

		@advocate=Advocate.find_by_name(params[:login_name])
		if params[:login_pass] == @advocate.password
		
                              render :text => "yes"
		else
		     render :text => "no"

		end
	end
	def new
                   
	end
	def create
		@advocate = Advocate.new(:name => params[:name])
		@advocate.save
	end
end

ad/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  skip_before_action :verify_authenticity_token
  
end

ad/app/controllers/informations_controller.rb
class InformationsController < ApplicationController
end

ad/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
end

ad/app/helpers/admin/advertisers_helper.rb
module Admin::AdvertisersHelper
end

ad/app/helpers/advertisers_helper.rb
module AdvertisersHelper
end

ad/app/helpers/advertises_helper.rb
module AdvertisesHelper
end

ad/app/helpers/advocates_helper.rb
module AdvocatesHelper
end

ad/app/helpers/application_helper.rb
module ApplicationHelper
end

ad/app/helpers/informations_helper.rb
module InformationsHelper
end

ad/app/helpers/tasks_helper.rb
module TasksHelper
end

ad/app/views/admin/advertisers/edit.html.erb
<%= form_for @advertisers, :url => { :controller => 'advertisers', :action => 'update', :id => @advertisers } do |f| %>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>
    <%= f.label :name, "Advertiser_id" %>
    <%= f.text_field :advertiser_id %>
     <%= f.label :name, "Email" %>
    <%= f.text_field :email %>
    <%= f.label :name, "phone" %>
    <%= f.text_field :phone %>
    <%= f.label :name, "Account" %>
    <%= f.text_field :account %>
    <%= f.label :name, "Password" %>
    <%= f.text_field :password %>
    <%= f.label :name, "Count" %>
    <%= f.text_field :count %>
    
    <%= f.submit "Update" %>
<% end %>

ad/app/views/admin/advertisers/index.html.erb
<%= form_tag selected_admin_advertisers_path do %>
<%= select_tag(:option, options_for_select([['advertiser_id', 'advertiser_id'], ['name', "name"], ['email', 'email'], ['phone', 'phone'], ['account', 'account'], ['password','password'], ['count', 'count']] )) %>
<%= text_field_tag "keyword" %>
<%= submit_tag "seach" %>
<% end %>
<table>
<tr>
<th>name</th>
<th>advertiser_id</th>
<th>email</th>
<th>phone</th>
<th>account</th>
<th>password</th>
<th>count</th>
</tr>
<% @advertisers.each do |advertiser| %>
<tr>
<td><%= advertiser.name %></td>
<td><%= advertiser.advertiser_id %></td>
<td><%= advertiser.email %></td>
<td><%= advertiser.phone %></td>
<td><%= advertiser.account %></td>
<td><%= advertiser.password %></td>
<td><%= advertiser.count %></td>
</tr>
<% end %>
</table>

ad/app/views/admin/advertisers/selected.html.erb
<table class="table">
<tr>
<th>name</th>
<th>advertiser_id</th>
<th>email</th>
<th>phone</th>
<th>account</th>
<th>password</th>
<th>count</th>
</tr>
<% @advertisers.each do |advertiser| %>
<tr>
<td><%= advertiser.name %></td>
<td><%= advertiser.advertiser_id %></td>
<td><%= advertiser.email %></td>
<td><%= advertiser.phone %></td>
<td><%= advertiser.account %></td>
<td><%= advertiser.password %></td>
<td><%= advertiser.count %></td>
 <th><%= link_to 'Edit', edit_admin_advertiser_path(advertiser) %></th>
 <th><%= button_to 'Delete', admin_advertiser_path(advertiser), :method => :delete, :data => { :confirm => "Are you sure?" } %></th>
</tr>
<% end %>
</table>



 

ad/app/views/admin/advertises/creat.html.erb
<% @advertises.each do |advertise| %>
<tr>
<td><%= advertise.advertise_id %></td>


</tr>

ad/app/views/admin/advertises/index.html.erb
<%= form_tag selected_admin_advertises_path do %>
<%= select_tag(:option, options_for_select([['advertiser_id', 'advertiser_id'], ['advertise_id', "advertise_id"], ['title', 'title'], ['content', 'content'], ['start_date', 'start_date'], ['end_date','end_date'], ['location', 'location']] )) %>
<%= text_field_tag "keyword" %>
<%= submit_tag "seach" %>
<% end %>

ad/app/views/admin/advertises/selected.html.erb
<table>
<tr>
<th>advertise_id</th>
<th>advertiser_id</th>
<th>title</th>
<th>content</th>
<th>start_date</th>
<th>end_date</th>
<th>location</th>
</tr>
<% @advertises.each do |advertise| %>
<tr>
<td><%= advertise.advertise_id %></td>
<td><%= advertise.advertiser_id %></td>
<td><%= advertise.title %></td>
<td><%= advertise.content %></td>
<td><%= advertise.start_date %></td>
<td><%= advertise.end_date %></td>
<td><%= advertise.location %></td>
<th><%= link_to 'link',  :controller => 'advertises', :action => 'show', :id => advertise  %> </th>
</tr>
<% end %>
</table>



 

ad/app/views/admin/advertises/show.html.erb
<table class="table">
<tr>
<th>name</th>
<th>advertiser_id</th>
<th>email</th>
<th>phone</th>
<th>account</th>
<th>password</th>
<th>count</th>
</tr>
<td><%= @advertises.name %></td>
<td><%= @advertises.advertiser_id %></td>
<td><%= @advertises.email %></td>
<td><%= @advertises.phone %></td>
<td><%= @advertises.account %></td>
<td><%= @advertises.password %></td>
<td><%= @advertises.count %></td>
</table>

ad/app/views/admin/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ad</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">
  <%= render "admin/common/navbar" %>
  <%= yield %>
</div>
  <%= render "admin/common/footer" %>

</body>
</html>

ad/app/views/advertisers/index.html.erb
<%= form_tag selected_advertisers_path do %>
<%= select_tag(:option, options_for_select([['advertiser_id', 'advertiser_id'], ['name', "name"], ['email', 'email'], ['phone', 'phone'], ['account', 'account'], ['password','password'], ['count', 'count']] )) %>
<%= text_field_tag "keyword" %>
<%= submit_tag "seach" %>

<% end %>

ad/app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">Copyright ©2014 Rails101s
    <br>Design by <a href="http://sdlong.logdown.com" target=_new>sdlong</a>
  </p>
</footer>

ad/app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">hi</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to("登入", '#') %> </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

ad/app/views/common/_navbar_left.html.erb
<nav class="navbar navbar-left navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
   

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <li> <%= link_to("advertiser", :controller => 'advertisers', :action => 'index') %> </li></br>
        <ul class="nav navbar-nav navbar-left">
        <li> <%= link_to("advertise",:controller => 'advertises', :action => 'index') %> </li></br>
    </ul>
    
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

   
  

ad/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ad</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">
  <%= render "common/navbar" %>
  
  <%= render "common/navbar_left" %>
  <%= yield %>
</div>
  <%= render "common/footer" %>

</body>
</html>